<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/DataCleaning2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Extension Data Types

Missing data handling for some numerical data types such as integers and Booleans was incomplete.<br> As a result, when missing data was introduced into such data, pandas converted the data type to float64 and used np.nan to represent null values.<br>
More recently, pandas has developed an extension type system allowing for new data types to be added even if they are not supported natively by NumPy

In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1 , 2 , 3 , None])

In [3]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [4]:
s[3]

np.float64(nan)

In [5]:
s[3] is None

False

In [6]:
s[3] is np.nan

False

In [7]:
s.dtype

dtype('float64')

In [8]:
print('Legacy behavior of using float64 data type and np.nan for missing values')

Legacy behavior of using float64 data type and np.nan for missing values

In [9]:
s = pd.Series([1 , 2 , 3 , np.nan] , dtype = pd.Int64Dtype())

In [10]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [11]:
print('NA for missing value in extension type array')

NA for missing value in extension type array

In [12]:
s[3]

In [13]:
s[3] is pd.NA

True

In [14]:
s[3] is np.nan

False

In [15]:
s[3] is None

False

## String Manipulation

### Python Built in String Object Method

In [16]:
val = 'My , name , is , Mamun'

In [17]:
val.split(',')

['My ', ' name ', ' is ', ' Mamun']

In [18]:
piece = [x.strip() for x in val.split(',')]

In [19]:
piece

['My', 'name', 'is', 'Mamun']

In [20]:
'::'.join(piece)

'My::name::is::Mamun'

In [21]:
'Mamun' in piece

True

In [22]:
val.index(',')

3

In [23]:
val.find(',')

3

In [24]:
val.index('.')

ValueError: substring not found

In [25]:
val.find('.')

-1

In [26]:
print('The difference between find and index is that find will output -1 if the augument is not found wherease index will raise error')

The difference between find and index is that find will output -1 if the augument is not found wherease index will raise error

In [27]:
val.count(',')

3

In [28]:
val.replace(',' , '.')

'My . name . is . Mamun'

In [29]:
s = 'avavavavavava'
s.count('avav')             # Only ouputs non overlapping counts

3

In [30]:
s.endswith('a')

True

In [31]:
s.startswith('a')

True

In [32]:
('yo').join(['How' , 'are' , 'you'])

'Howyoareyoyou'

In [33]:
s.find('a')

0

In [34]:
s.rfind('a')

12

In [35]:
s.rfind('v')

11

In [36]:
s = 'a'
s.rjust(3 , '-')

'--a'

In [37]:
s.ljust(3 , '-')

'a--'

In [38]:
s.center(5 , '+')

'++a++'

### Regular Expression

In [39]:
print('Regular expression provide a flexible way to search or match string pattern in text')

Regular expression provide a flexible way to search or match string pattern in text

In [40]:
print('A single expression commonly known as regex is a string formed according to the regular expression language')

A single expression commonly known as regex is a string formed according to the regular expression language

In [41]:
print('Python re module had function breifly for pattern matching , substitution and splitting')

Python re module had function breifly for pattern matching , substitution and splitting

In [42]:
import re

In [43]:
s = 'fpp      bar \t baz \tqux'

In [44]:
re.split(r'\s+' , s)

['fpp', 'bar', 'baz', 'qux']

In [45]:
print('Here the string is first complied to regex and then split method is applied')

Here the string is first complied to regex and then split method is applied

In [46]:
print('We can compile on our own and then apply split')

We can compile on our own and then apply split

In [47]:
t = re.compile(r'\s+')

In [48]:
t.split(s)

['fpp', 'bar', 'baz', 'qux']

In [49]:
t.findall(s)

['      ', ' \t ', ' \t']

In [50]:
re.findall(r'\s+' , s)

['      ', ' \t ', ' \t']

In [51]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

In [52]:
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}"

In [53]:
regex = re.compile(pattern , flags = re.IGNORECASE)

In [54]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [55]:
print('match and search are closely related to findall , while findall returns all matches in string , search returns only the first match and match more rigidly only matches at the begining of the string')

match and search are closely related to findall , while findall returns all matches in string , search returns only the first match and match more rigidly only matches at the begining of the string

In [56]:
s = 'cat@dog@cat'

In [57]:
re.findall(r'cat' , s)

['cat', 'cat']

In [58]:
print(re.finditer(r'cat' , s))         # returns an iterator

<callable_iterator object at 0x791fcdcad000>

In [59]:
print(re.match(r'cat' , s))

<re.Match object; span=(0, 3), match='cat'>

In [60]:
print(re.match(r'dog' , s))

None

In [61]:
print(re.search(r'dog' , s))

<re.Match object; span=(4, 7), match='dog'>

In [62]:
print(re.split(r'@' , s))

['cat', 'dog', 'cat']

In [63]:
m = regex.search(text)

In [64]:
m

In [65]:
print(regex.match(text))

None

In [66]:
print(regex.sub('Redacted' , text))

Dave Redacted
Steve Redacted
Rob Redacted
Ryan Redacted

In [67]:
pattern = r'([A-Z0-9,_%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,})'

In [68]:
regex = re.compile(pattern , flags = re.IGNORECASE)

In [69]:
m = regex.match('wesm@bright.net')

In [70]:
m.groups()

('wesm', 'bright', 'net')

In [71]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [72]:
print('sub also has access to groups in each match using special symbols like \\1 and \\2. The symbol \\1 corresponds to the first matched group, \\2 corresponds to the second')

sub also has access to groups in each match using special symbols like \1 and \2. The symbol \1 corresponds to the first matched group, \2 corresponds to the second

In [73]:
print(regex.sub(r'Username : \1 ; Domain : \2 ; Suffix : \3'  , text))

Dave Username : dave ; Domain : google ; Suffix : com
Steve Username : steve ; Domain : gmail ; Suffix : com
Rob Username : rob ; Domain : gmail ; Suffix : com
Ryan Username : ryan ; Domain : yahoo ; Suffix : com

### String Functions in pandas

In [74]:
data = {
    "Dave": "dave@google.com",
    "Steve": "steve@gmail.com",
    "Rob": "rob@gmail.com",
    "Wes": np.nan
    }

In [75]:
data = pd.Series(data)

In [76]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [77]:
print('All string operation can be applied using .apply or .map but it stucks on nap values')

All string operation can be applied using .apply or .map but it stucks on nap values

In [78]:
at_positions = [x.find('@') for x in data]

AttributeError: 'float' object has no attribute 'find'

In [79]:
print("Due to presence of nan it raises error 'float' object has no attribute 'find'")

Due to presence of nan it raises error 'float' object has no attribute 'find'

In [80]:
at_positions = data.str.find('@')

In [81]:
print('Hence str attribute is used')

Hence str attribute is used

In [82]:
data.str.contains('@')

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [83]:
print('As a result of the opertion the returned datatype of str.contains is object and not boolean')

As a result of the opertion the returned datatype of str.contains is object and not boolean

In [84]:
data_as_string = data.astype('string')

In [85]:
data_as_string

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [86]:
data_as_string.str.contains('@')

Dave     True
Steve    True
Rob      True
Wes      <NA>
dtype: boolean

In [87]:
print('Here we got boolean')

Here we got boolean

In [88]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,})'

In [89]:
data.str.findall(pattern , flags = re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [90]:
matches = data.str.findall(pattern , flags = re.IGNORECASE).str[0]

In [91]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [92]:
print('Ending str[0] gives the first match for each case')

Ending str[0] gives the first match for each case

In [93]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [94]:
data.str.extract(pattern , flags = re.IGNORECASE)

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [95]:
print('Extract will return the first occurance of the pattern but as a dataFrame')

Extract will return the first occurance of the pattern but as a dataFrame

In [96]:
raw_data = [
    "  user1@gmail.com, USER2@yahoo.com !!  ",
    "john.doe@company.co.uk",
    "INVALID_TEXT_NO_EMAIL",
    "  SPAM: admin@test.org  ",
    np.nan
]

In [97]:
s = pd.Series(raw_data)

In [98]:
s

0      user1@gmail.com, USER2@yahoo.com !!
1                     john.doe@company.co.uk
2                      INVALID_TEXT_NO_EMAIL
3                     SPAM: admin@test.org
4                                        NaN
dtype: object

In [99]:
s.str.cat(['a' , 'b' , 'c' , 'd' , 'e'])

0      user1@gmail.com, USER2@yahoo.com !!  a
1                     john.doe@company.co.ukb
2                      INVALID_TEXT_NO_EMAILc
3                     SPAM: admin@test.org  d
4                                         NaN
dtype: object

In [100]:
s.str.contains('a')

0     True
1     True
2    False
3     True
4      NaN
dtype: object

In [101]:
s.str.count('@')

0    2.0
1    1.0
2    0.0
3    1.0
4    NaN
dtype: float64

In [102]:
s.str.extract(r'([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})')

                        0
0         user1@gmail.com
1  john.doe@company.co.uk
2                     NaN
3          admin@test.org
4                     NaN

In [103]:
s.str.endswith('k')

0    False
1     True
2    False
3    False
4      NaN
dtype: object

In [104]:
s.str.startswith(' ')

0     True
1    False
2    False
3     True
4      NaN
dtype: object

In [105]:
s.str.findall(r'([A-Z0-9]+@[A-Z0-9]+\.[A-Z]{2,4})' , flags = re.IGNORECASE)

0    [user1@gmail.com, USER2@yahoo.com]
1                      [doe@company.co]
2                                    []
3                      [admin@test.org]
4                                   NaN
dtype: object

In [106]:
s.str.get(1)

0
1      o
2      N
3
4    NaN
dtype: object

In [107]:
s.str.len()

0    39.0
1    22.0
2    21.0
3    24.0
4     NaN
dtype: float64

In [108]:
s.str.split()

0    [user1@gmail.com,, USER2@yahoo.com, !!]
1                   [john.doe@company.co.uk]
2                    [INVALID_TEXT_NO_EMAIL]
3                    [SPAM:, admin@test.org]
4                                        NaN
dtype: object