<a href="https://colab.research.google.com/github/Devil-92/100_Days_of_ML/blob/main/Naives_Bayes_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/breast-cancer-wisconsin-data")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'breast-cancer-wisconsin-data' dataset.
Path to dataset files: /kaggle/input/breast-cancer-wisconsin-data

In [2]:
import pandas as pd
import numpy as np

In [10]:
%cd "/kaggle/input/breast-cancer-wisconsin-data"

/kaggle/input/breast-cancer-wisconsin-data

In [13]:
df = pd.read_csv('/kaggle/input/breast-cancer-wisconsin-data/data.csv')

In [15]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [16]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [18]:
df.shape

(569, 33)

In [20]:
df['Unnamed: 32'].isna().sum()

np.int64(569)

In [25]:
X = df.drop(['Unnamed: 32' , 'id' , 'diagnosis'] , axis = 1)
y = df['diagnosis']

In [26]:
X.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [27]:
classes = np.unique(y)

In [29]:
classes

array(['B', 'M'], dtype=object)

In [47]:
means = [[xtrain[ytrain == c].mean() for c in classes]]

In [57]:
prior = [len(ytrain[ytrain == c]) / len(ytrain) for c in classes]

In [58]:
prior

[0.621978021978022, 0.378021978021978]

In [49]:
from sklearn.model_selection import train_test_split

In [37]:
xtrain , xtest , ytrain , ytest = train_test_split(X , y , test_size = 0.2)

In [90]:
class Naives_Bayes :
  def fit(self , X_train , y_train) :
    self.classes = np.unique(y_train)
    self.priors = [len(y_train[y_train == c]) / len(y_train) for c in self.classes]

    self.means = [X_train[y_train == c].mean() for c in self.classes]
    self.stds = [X_train[y_train == c].std() for c in self.classes]

  def likelihood_calc(self , row , class_idx) :
    elipson = 10e-9
    likelihood = 1
    for f in row.index :
      mean = self.means[class_idx][f]
      std = self.stds[class_idx][f] + elipson
      likelihood *= (1 / np.sqrt(2 * np.pi * std ** 2) * np.exp((-1) * ((row[f] - mean) ** 2) / (2 * std ** 2)))
    return likelihood

  def predict(self , X) :
    y_pred = []
    for _ , row in X.iterrows() :
      posterior = []
      for i in range(len(self.classes)) :
        likelihood = self.likelihood_calc(row , i)
        posterior.append(likelihood * self.priors[i])
      y_pred.append(self.classes[np.argmax(posterior)])
    return y_pred

In [91]:
nb = Naives_Bayes()

In [92]:
nb.fit(xtrain , ytrain)

In [93]:
pred = nb.predict(xtest)

In [94]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(ytest , pred)

In [98]:
print(np.round(acc * 100 , 2))

92.98